version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # 假设您的应用监听在 8080 端口
    # environment:
    #   - "ENV_VAR_NAME=value"  # 如果您的应用需要环境变量，可以在这里设置
    volumes:
      - .:/app  # 将当前目录映射到容器的工作目录
      - go-modules:/go/pkg/mod  # 缓存 go modules，加快构建速度

volumes:
  go-modules:  # 定义 go-modules 卷
